services:
  cpacodexkeeper:
    build: .
    container_name: cpacodexkeeper
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./disabled_accounts.json.lock:/app/disabled_accounts.json.lock
      - ./disabled_accounts.json:/app/disabled_accounts.json
      - ./delete_blocked_accounts.json:/app/delete_blocked_accounts.json
